spring.datasource.url=jdbc:postgresql://localhost:5432/TaskManager
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt-secret="C6UlILsE6GJwNqwCTkkvJj9O653yJUoteWMLfYyrc3vaGrrTOrJFAUD1wEBnnposzcQl"
spring.mail.username=${ApiName}
spring.mail.password=${ApiKey}
sender.email=${SENDER_MAIL}
cloud.name=${CLOUDE_NAME}
cloud.key=${API_KEY}
cloud.secret=${API_SECRET}
logging.level.com.Project4.TaskManager=DEBUG